### YamlMime:ManagedReference
items:
- uid: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime
  commentId: T:Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime
  id: IXamarinHostApplicationLifetime
  parent: Microsoft.Extensions.Hosting
  children:
  - Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationResuming
  - Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationSleeping
  langs:
  - csharp
  - vb
  name: IXamarinHostApplicationLifetime
  nameWithType: IXamarinHostApplicationLifetime
  fullName: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime
  type: Interface
  source:
    remote:
      path: src/Abstractions/IXamarinHostApplicationLifetime.cs
      branch: master
      repo: https://github.com/jamiewest/XamarinFormsHost.git
    id: IXamarinHostApplicationLifetime
    path: ../src/Abstractions/IXamarinHostApplicationLifetime.cs
    startLine: 5
  assemblies:
  - West.Extensions.XamarinHosting.Abstractions
  namespace: Microsoft.Extensions.Hosting
  summary: "\nAllows consumers to perform cleanup during application sleep/resume.\n"
  example: []
  syntax:
    content: 'public interface IXamarinHostApplicationLifetime : IHostApplicationLifetime'
    content.vb: >-
      Public Interface IXamarinHostApplicationLifetime

          Inherits IHostApplicationLifetime
  inheritedMembers:
  - Microsoft.Extensions.Hosting.IHostApplicationLifetime.StopApplication
  - Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStarted
  - Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStopping
  - Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStopped
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationSleeping
  commentId: P:Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationSleeping
  id: ApplicationSleeping
  parent: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime
  langs:
  - csharp
  - vb
  name: ApplicationSleeping
  nameWithType: IXamarinHostApplicationLifetime.ApplicationSleeping
  fullName: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationSleeping
  type: Property
  source:
    remote:
      path: src/Abstractions/IXamarinHostApplicationLifetime.cs
      branch: master
      repo: https://github.com/jamiewest/XamarinFormsHost.git
    id: ApplicationSleeping
    path: ../src/Abstractions/IXamarinHostApplicationLifetime.cs
    startLine: 10
  assemblies:
  - West.Extensions.XamarinHosting.Abstractions
  namespace: Microsoft.Extensions.Hosting
  summary: "\nTriggered when the application has gone to sleep.\n"
  example: []
  syntax:
    content: ILifecycleRegister ApplicationSleeping { get; }
    parameters: []
    return:
      type: Microsoft.Extensions.Hosting.ILifecycleRegister
    content.vb: ReadOnly Property ApplicationSleeping As ILifecycleRegister
  overload: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationSleeping*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationResuming
  commentId: P:Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationResuming
  id: ApplicationResuming
  parent: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime
  langs:
  - csharp
  - vb
  name: ApplicationResuming
  nameWithType: IXamarinHostApplicationLifetime.ApplicationResuming
  fullName: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationResuming
  type: Property
  source:
    remote:
      path: src/Abstractions/IXamarinHostApplicationLifetime.cs
      branch: master
      repo: https://github.com/jamiewest/XamarinFormsHost.git
    id: ApplicationResuming
    path: ../src/Abstractions/IXamarinHostApplicationLifetime.cs
    startLine: 15
  assemblies:
  - West.Extensions.XamarinHosting.Abstractions
  namespace: Microsoft.Extensions.Hosting
  summary: "\nTriggered when the application has resumed.\n"
  example: []
  syntax:
    content: ILifecycleRegister ApplicationResuming { get; }
    parameters: []
    return:
      type: Microsoft.Extensions.Hosting.ILifecycleRegister
    content.vb: ReadOnly Property ApplicationResuming As ILifecycleRegister
  overload: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationResuming*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Microsoft.Extensions.Hosting
  commentId: N:Microsoft.Extensions.Hosting
  name: Microsoft.Extensions.Hosting
  nameWithType: Microsoft.Extensions.Hosting
  fullName: Microsoft.Extensions.Hosting
- uid: Microsoft.Extensions.Hosting.IHostApplicationLifetime.StopApplication
  commentId: M:Microsoft.Extensions.Hosting.IHostApplicationLifetime.StopApplication
  parent: Microsoft.Extensions.Hosting.IHostApplicationLifetime
  isExternal: true
  name: StopApplication()
  nameWithType: IHostApplicationLifetime.StopApplication()
  fullName: Microsoft.Extensions.Hosting.IHostApplicationLifetime.StopApplication()
  spec.csharp:
  - uid: Microsoft.Extensions.Hosting.IHostApplicationLifetime.StopApplication
    name: StopApplication
    nameWithType: IHostApplicationLifetime.StopApplication
    fullName: Microsoft.Extensions.Hosting.IHostApplicationLifetime.StopApplication
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Microsoft.Extensions.Hosting.IHostApplicationLifetime.StopApplication
    name: StopApplication
    nameWithType: IHostApplicationLifetime.StopApplication
    fullName: Microsoft.Extensions.Hosting.IHostApplicationLifetime.StopApplication
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStarted
  commentId: P:Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStarted
  parent: Microsoft.Extensions.Hosting.IHostApplicationLifetime
  isExternal: true
  name: ApplicationStarted
  nameWithType: IHostApplicationLifetime.ApplicationStarted
  fullName: Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStarted
- uid: Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStopping
  commentId: P:Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStopping
  parent: Microsoft.Extensions.Hosting.IHostApplicationLifetime
  isExternal: true
  name: ApplicationStopping
  nameWithType: IHostApplicationLifetime.ApplicationStopping
  fullName: Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStopping
- uid: Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStopped
  commentId: P:Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStopped
  parent: Microsoft.Extensions.Hosting.IHostApplicationLifetime
  isExternal: true
  name: ApplicationStopped
  nameWithType: IHostApplicationLifetime.ApplicationStopped
  fullName: Microsoft.Extensions.Hosting.IHostApplicationLifetime.ApplicationStopped
- uid: Microsoft.Extensions.Hosting.IHostApplicationLifetime
  commentId: T:Microsoft.Extensions.Hosting.IHostApplicationLifetime
  parent: Microsoft.Extensions.Hosting
  isExternal: true
  name: IHostApplicationLifetime
  nameWithType: IHostApplicationLifetime
  fullName: Microsoft.Extensions.Hosting.IHostApplicationLifetime
- uid: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationSleeping*
  commentId: Overload:Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationSleeping
  name: ApplicationSleeping
  nameWithType: IXamarinHostApplicationLifetime.ApplicationSleeping
  fullName: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationSleeping
- uid: Microsoft.Extensions.Hosting.ILifecycleRegister
  commentId: T:Microsoft.Extensions.Hosting.ILifecycleRegister
  parent: Microsoft.Extensions.Hosting
  name: ILifecycleRegister
  nameWithType: ILifecycleRegister
  fullName: Microsoft.Extensions.Hosting.ILifecycleRegister
- uid: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationResuming*
  commentId: Overload:Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationResuming
  name: ApplicationResuming
  nameWithType: IXamarinHostApplicationLifetime.ApplicationResuming
  fullName: Microsoft.Extensions.Hosting.IXamarinHostApplicationLifetime.ApplicationResuming
